### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by J4VIJ46** [J4VIJ46/name-gen#1]
# Todo list #
- [ ] Implement unit testing for name generation modules.
- [x] Rework options hierarchy
- [ ] Implement capitals option
- [ ] Implement special symbols option
- [ ] Explore stylistics, phonetics and other stuff
- [ ] Generation by syllables option
- [ ] Rework DRY implementation
